"""Tag with created_at and updated_at

Revision ID: b1adac79678a
Revises: 29b7a3a29c41
Create Date: 2025-10-06 23:33:39.970868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1adac79678a'
down_revision: Union[str, Sequence[str], None] = '29b7a3a29c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    # ### end Alembic commands ###
